
bulutyazilim_feedback_new:
    path:     /feedback/new
    defaults: { _controller: "BulutYazilimFeedbackBundle:Feedback:new" }

bulutyazilim_feedback_homepage:
    path:     /feedback/{status}
    defaults: { _controller: "BulutYazilimFeedbackBundle:FeedbackAdmin:index",status: 0 }

bulutyazilim_feedback_inbox:
    path:     /feedback/inbox
    defaults: { _controller: "BulutYazilimFeedbackBundle:Feedback:inbox" }

bulutyazilim_feedback_delete:
    path:     /admin/feedback/remove/{id}
    defaults: {_controller: "BulutYazilimFeedbackBundle:FeedbackAdmin:delete" }
    methods: [DELETE]
bulutyazilim_feedback_mark_read:
    path:     /admin/feedback/mark/read/{id}
    defaults: {_controller: "BulutYazilimFeedbackBundle:FeedbackAdmin:markAs", type: 'read' }
bulutyazilim_feedback_mark_done:
    path:     /admin/feedback/mark/done/{id}
    defaults: {_controller: "BulutYazilimFeedbackBundle:FeedbackAdmin:markAs", type: 'done' }
bulutyazilim_feedback_reply:
    path:     /admin/feedback/reply/{id}
    defaults: {_controller: "BulutYazilimFeedbackBundle:FeedbackAdmin:reply"}
