services:
  bulutyazilim_feedback.extension:
    class: BulutYazilim\FeedbackBundle\Twig\FeedbackExtension
    arguments: ["@form.factory", "@twig", "@doctrine.orm.default_entity_manager", "%feedback_categories%"]
    tags:
      - { name: twig.extension }
