services:
  bulutyazilim_feedback.extension:
    class: BulutYazilim\FeedbackBundle\Twig\FeedbackExtension
    arguments: ["@service_container","@security.context"]
    tags:
      - { name: twig.extension }
